---
# tasks file for template
#

- name: Template | Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Template | Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      skip: true

- name: Template | Create Directories
  ansible.builtin.file:
    path: /opt/template
    state: directory
    owner: root
    group: root
    mode: 0750
